/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE studentsBaseService PLEASE EDIT ../students.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Students } from '../../domain/jmyx_prototype_db/students';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Students.service.ts
 */

/*
 * SCHEMA DB Students
 *
	{
		age: {
			type: 'Integer',
			required : true
		},
		class_count: {
			type: 'Integer',
			required : true
		},
		course_id: {
			type: 'Integer',
			required : true
		},
		create_time: {
			type: 'Date',
			required : true
		},
		isTrial: {
			type: 'Boolean',
			required : true
		},
		name: {
			type: 'String',
			required : true
		},
		nick_name: {
			type: 'String'
		},
		update_time: {
			type: 'Date',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		student_course: [{
			type: Schema.ObjectId,
			ref : "Students"
		}],
	}
 *
 */
@Injectable()
export class StudentsBaseService {

    contextUrl: string = environment.endpoint + '/students';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * StudentsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Students): Observable<Students> {
        return this.http
            .post<Students>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * StudentsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * StudentsService.findBystudent_course
    *   @description CRUD ACTION findBystudent_course
    *   @param Objectid key Id of model to search for
    *
    */
    findByStudent_course(id: string): Observable<Students[]> {
        return this.http
            .get<Students[]>(this.contextUrl + '/findBystudent_course/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * StudentsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Students> {
        return this.http
            .get<Students>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * StudentsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Students[]> {
        return this.http
            .get<Students[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * StudentsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Students): Observable<Students> {
        return this.http
            .post<Students>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
