/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE teachersBaseService PLEASE EDIT ../teachers.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Teachers } from '../../domain/jmyx_prototype_db/teachers';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Teachers.service.ts
 */

/*
 * SCHEMA DB Teachers
 *
	{
		create_time: {
			type: 'Date',
			required : true
		},
		name: {
			type: 'String',
			required : true
		},
		update_time: {
			type: 'Date',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		teacher_class: {
			type: Schema.ObjectId,
			ref : "Teachers"
		},
	}
 *
 */
@Injectable()
export class TeachersBaseService {

    contextUrl: string = environment.endpoint + '/teachers';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * TeachersService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Teachers): Observable<Teachers> {
        return this.http
            .post<Teachers>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * TeachersService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TeachersService.findByteacher_class
    *   @description CRUD ACTION findByteacher_class
    *   @param Objectid key Id of model to search for
    *
    */
    findByTeacher_class(id: string): Observable<Teachers[]> {
        return this.http
            .get<Teachers[]>(this.contextUrl + '/findByteacher_class/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * TeachersService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Teachers> {
        return this.http
            .get<Teachers>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TeachersService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Teachers[]> {
        return this.http
            .get<Teachers[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * TeachersService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Teachers): Observable<Teachers> {
        return this.http
            .post<Teachers>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
